//No código Sincrono ele executa linha por linha na sequencia.
//No assincrono ele lê a linha assincrona mas não espera ela terminar de executar para pular para a próxima, ela continua rodando enquanto vai rodando as próximas



// Código SÍNCRONO
let nome = 'Felipe'
let sobrenome = 'Matheus'
let completo = nome + ' ' + sobrenome

// Código Assíncrono
let nome2 = 'Felipe'
let sobrenome2 = 'Matheus'
let temperatura = Maquininha.pegarTemperatura() //Assincrono
let completo2 = nome2 + ' ' + sobrenome2

